# Generated by Django 5.1.2 on 2024-12-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstnane',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastnane',
            new_name='lastname',
        ),
    ]
